version: '3'
services:
  node-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: qa-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    container_name: node-api
    external_links:
      - mongo-db
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo-db
    volumes:
      - qa-db:/data/db
volumes:
  qa-db:
